"""initialize alembic

Revision ID: 9a9ea24dec38
Revises: 5d04c8fa826e
Create Date: 2022-01-07 17:48:12.675066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9ea24dec38'
down_revision = '5d04c8fa826e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conf_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_win_loss', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_team_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_team_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_team_stats_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_win_loss', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_team_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_team_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_team_stats_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name='matchups_away_team_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['away_team_stats_id'], ['team_weekly_stats.id'], name='matchups_away_team_stats_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name='matchups_home_team_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_stats_id'], ['team_weekly_stats.id'], name='matchups_home_team_stats_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name='matchups_week_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='matchups_pkey')
    )
    # ### end Alembic commands ###
